version: "3.7"

services:

  app:
    build:
      context: ./
    container_name: tbnb
    volumes:
      - .:/var/www/html/app
    environment:
      - PORT=80
    ports:
      - 8081:80
    depends_on:
      - db
    networks:
      - tbnb-network

  db:
    image: postgres:alpine
    container_name: tbnb-db
    volumes:
      - ./docker/pgsqldata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=default
      - POSTGRES_USER=default
      - POSTGRES_PASSWORD=secret
    networks:
      - tbnb-network

networks:
  tbnb-network:
      driver: bridge
